---
- name: Stop VirtualBox VMs
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    vms:
      - ubuntu1
      - kali-linux-2025.4-virtualbox-amd64

  tasks:
    - name: Get list of running VMs
      ansible.builtin.command: VBoxManage list runningvms
      register: running_vms
      changed_when: false

    - name: Save state and stop running VMs
      ansible.builtin.command: VBoxManage controlvm "{{ item }}" savestate
      loop: "{{ vms }}"
      when: item in running_vms.stdout
