---
- name: Stop EC2 instances
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Stop instances
      community.aws.ec2_instance:
        instance_ids:
          - i-0e837e136f8228d24  # bobasoft_ubuntu1
        region: us-east-1
        state: stopped
        wait: true
