---
- name: Terminate EC2 instances
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Terminate instances
      community.aws.ec2_instance:
        instance_ids:
          - i-0213dff343540aa38  # k8s-infographics
        region: us-east-1
        state: terminated
        wait: true
